[system]
# Load language from environment variable(It is set by the hook)
language = "${env:DBGPT_LANG:-zh}"
api_keys = []
encrypt_key = "your_secret_key"

# Server Configurations
[service.web]
host = "0.0.0.0"
port = 5670

[service.web.database]
type = "sqlite"
path = "pilot/meta_data/dbgpt.db"
[service.model.worker]
host = "127.0.0.1"

[rag.storage]
[rag.storage.vector]
type = "chroma"
persist_path = "pilot/data"

# Model Configurations
[models]
[[models.llms]]
name = "qwen3"
provider = "proxy/openai"
api_base = "http://192.168.128.160:9997/v1"
api_url = "http://192.168.128.160:9997/v1"
api_key = "sk-inference"

[[models.embeddings]]
name = "bge-m3"
provider = "proxy/openai"
api_url = "http://192.168.128.160:9997/v1/embeddings"
api_key = "sk-inference"
model = "bge-m3"

# [[models.rerankers]]
# type = "reranker"
# name = "bge-reranker-v2-m3"
# provider = "proxy/openapi"
# api_url = "http://192.168.128.160:9997/v1/rerank" 
# api_key = "sk-inference"
# 

[[models.rerankers]]
type = "reranker"
name = "bge-reranker-v2-m3"
provider = "proxy/infiniai"
api_url = "http://192.168.128.160:9997/v1/rerank" 
# api_key = "sk-inference"
api_key = "${env:INFINIAI_API_KEY:-sk-kk6ej7jfzwkqrf75}" 